name: Notify Telegram on Commit

on:
  push:
    branches:
      - main  # You can change this to the branch you want to monitor

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Ensures the repository is checked out

    - name: Send Telegram message
      env:
        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        commit_message=$(git log -1 --pretty=%B)
        commit_url=${{ github.event.head_commit.url }}
        repo_name=${{ github.repository }}
        repo_url="https://github.com/${{ github.repository }}"


        if [ -z "$commit_message" ]; then commit_message="No commit message"; fi
        if [ -z "$commit_url" ]; then commit_url="No URL available"; fi
        if [ -z "$repo_name" ]; then repo_name="Unknown repository"; fi

        message="New solution added to $repo_name $commit_message - $repo_url"
        
        curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
        -d chat_id=${CHAT_ID} \
        -d text="$message"
