name: Notify Telegram on Commit

on:
  push:
    branches:
      - main  # You can change this to the branch you want to monitor

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Ensures the repository is checked out
    
    # Debug step: Check BOT_TOKEN and CHAT_ID environment variables
    - name: Debug: Check environment variables
      run: |
        if [ -z "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]; then
          echo "Error: TELEGRAM_BOT_TOKEN is not set or is empty"
          exit 1
        else
          echo "TELEGRAM_BOT_TOKEN is set."
        fi

        if [ -z "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
          echo "Error: TELEGRAM_CHAT_ID is not set or is empty"
          exit 1
        else
          echo "TELEGRAM_CHAT_ID is set."
        fi

    - name: Send Telegram message
      env:
        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        commit_message=$(git log -1 --pretty=%B)
        commit_url=${{ github.event.head_commit.url }}
        committer_name=${{ github.event.head_commit.committer.name }}
        repo_name=${{ github.repository }}

        if [ -z "$commit_message" ]; then commit_message="No commit message"; fi
        if [ -z "$commit_url" ]; then commit_url="No URL available"; fi
        if [ -z "$committer_name" ]; then committer_name="Unknown committer"; fi
        if [ -z "$repo_name" ]; then repo_name="Unknown repository"; fi

        message="New commit to $repo_name by $committer_name: $commit_message - $commit_url"
        
        curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
        -d chat_id=${CHAT_ID} \
        -d text="$message"
